<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="5" total="8" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="145110" started-at="2014-04-15T02:51:39Z" finished-at="2014-04-15T02:54:04Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="145110" started-at="2014-04-15T02:51:39Z" finished-at="2014-04-15T02:54:04Z">
      <class name="hub.test.LoginTest">
        <test-method status="PASS" signature="Startup(java.lang.String)[pri:0, instance:hub.test.LoginTest@72d69a74]" name="Startup" is-config="true" duration-ms="67761" started-at="2014-04-15T10:51:39Z" finished-at="2014-04-15T10:52:47Z">
          <params>
            <param index="0">
              <value is-null="true"/>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Startup -->
        <test-method status="PASS" signature="init()[pri:0, instance:hub.test.LoginTest@72d69a74]" name="init" is-config="true" duration-ms="62" started-at="2014-04-15T10:52:47Z" finished-at="2014-04-15T10:52:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method status="FAIL" signature="testLogin(java.lang.Class, [Ljava.lang.String;)[pri:0, instance:hub.test.LoginTest@72d69a74]" name="testLogin" duration-ms="16369" started-at="2014-04-15T10:52:47Z" description="Test Login" data-provider="Data-Provider-Function" finished-at="2014-04-15T10:53:03Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[class java.lang.String]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[[Ljava.lang.String;@70556101]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.fail(Assert.java:101)
	at hub.utilities.UserHubLoginUtil.testHubLoginSuccess(UserHubLoginUtil.java:81)
	at hub.test.LoginTest.testLogin(LoginTest.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:335)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:330)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogin -->
        <test-method status="PASS" signature="reinitializeBrowser()[pri:0, instance:hub.test.LoginTest@72d69a74]" name="reinitializeBrowser" is-config="true" duration-ms="3697" started-at="2014-04-15T10:53:03Z" finished-at="2014-04-15T10:53:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reinitializeBrowser -->
        <test-method status="PASS" signature="testLogin(java.lang.Class, [Ljava.lang.String;)[pri:0, instance:hub.test.LoginTest@72d69a74]" name="testLogin" duration-ms="707" started-at="2014-04-15T10:53:07Z" description="Test Login" data-provider="Data-Provider-Function" finished-at="2014-04-15T10:53:08Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[class java.lang.String]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[[Ljava.lang.String;@24bcf6c6]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogin -->
        <test-method status="PASS" signature="reinitializeBrowser()[pri:0, instance:hub.test.LoginTest@72d69a74]" name="reinitializeBrowser" is-config="true" duration-ms="3889" started-at="2014-04-15T10:53:08Z" finished-at="2014-04-15T10:53:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reinitializeBrowser -->
        <test-method status="PASS" signature="testLogin(java.lang.Class, [Ljava.lang.String;)[pri:0, instance:hub.test.LoginTest@72d69a74]" name="testLogin" duration-ms="1041" started-at="2014-04-15T10:53:12Z" description="Test Login" data-provider="Data-Provider-Function" finished-at="2014-04-15T10:53:13Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[class java.lang.String]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[[Ljava.lang.String;@71ed5401]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogin -->
        <test-method status="PASS" signature="reinitializeBrowser()[pri:0, instance:hub.test.LoginTest@72d69a74]" name="reinitializeBrowser" is-config="true" duration-ms="3866" started-at="2014-04-15T10:53:13Z" finished-at="2014-04-15T10:53:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reinitializeBrowser -->
        <test-method status="FAIL" signature="testLogin(java.lang.Class, [Ljava.lang.String;)[pri:0, instance:hub.test.LoginTest@72d69a74]" name="testLogin" duration-ms="938" started-at="2014-04-15T10:53:17Z" description="Test Login" data-provider="Data-Provider-Function" finished-at="2014-04-15T10:53:18Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[class java.lang.String]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[[Ljava.lang.String;@7553c244]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.fail(Assert.java:101)
	at hub.utilities.UserHubLoginUtil.testHubLoginEmpty(UserHubLoginUtil.java:108)
	at hub.test.LoginTest.testLogin(LoginTest.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:335)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:330)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogin -->
        <test-method status="PASS" signature="reinitializeBrowser()[pri:0, instance:hub.test.LoginTest@72d69a74]" name="reinitializeBrowser" is-config="true" duration-ms="3631" started-at="2014-04-15T10:53:18Z" finished-at="2014-04-15T10:53:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reinitializeBrowser -->
        <test-method status="FAIL" signature="testLogin(java.lang.Class, [Ljava.lang.String;)[pri:0, instance:hub.test.LoginTest@72d69a74]" name="testLogin" duration-ms="865" started-at="2014-04-15T10:53:21Z" description="Test Login" data-provider="Data-Provider-Function" finished-at="2014-04-15T10:53:22Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[class java.lang.String]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[[Ljava.lang.String;@4df73a89]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.fail(Assert.java:101)
	at hub.utilities.UserHubLoginUtil.testHubLoginEmpty(UserHubLoginUtil.java:108)
	at hub.test.LoginTest.testLogin(LoginTest.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:335)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:330)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogin -->
        <test-method status="PASS" signature="reinitializeBrowser()[pri:0, instance:hub.test.LoginTest@72d69a74]" name="reinitializeBrowser" is-config="true" duration-ms="3895" started-at="2014-04-15T10:53:22Z" finished-at="2014-04-15T10:53:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reinitializeBrowser -->
        <test-method status="FAIL" signature="testLogin(java.lang.Class, [Ljava.lang.String;)[pri:0, instance:hub.test.LoginTest@72d69a74]" name="testLogin" duration-ms="852" started-at="2014-04-15T10:53:26Z" description="Test Login" data-provider="Data-Provider-Function" finished-at="2014-04-15T10:53:27Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[class java.lang.String]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[[Ljava.lang.String;@2224205c]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.fail(Assert.java:101)
	at hub.utilities.UserHubLoginUtil.testHubLoginEmpty(UserHubLoginUtil.java:108)
	at hub.test.LoginTest.testLogin(LoginTest.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:335)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:330)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogin -->
        <test-method status="PASS" signature="reinitializeBrowser()[pri:0, instance:hub.test.LoginTest@72d69a74]" name="reinitializeBrowser" is-config="true" duration-ms="3720" started-at="2014-04-15T10:53:27Z" finished-at="2014-04-15T10:53:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reinitializeBrowser -->
        <test-method status="PASS" signature="testLogin(java.lang.Class, [Ljava.lang.String;)[pri:0, instance:hub.test.LoginTest@72d69a74]" name="testLogin" duration-ms="749" started-at="2014-04-15T10:53:31Z" description="Test Login" data-provider="Data-Provider-Function" finished-at="2014-04-15T10:53:31Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[class java.lang.String]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[[Ljava.lang.String;@14264816]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogin -->
        <test-method status="PASS" signature="reinitializeBrowser()[pri:0, instance:hub.test.LoginTest@72d69a74]" name="reinitializeBrowser" is-config="true" duration-ms="5789" started-at="2014-04-15T10:53:31Z" finished-at="2014-04-15T10:53:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reinitializeBrowser -->
        <test-method status="FAIL" signature="testLogin(java.lang.Class, [Ljava.lang.String;)[pri:0, instance:hub.test.LoginTest@72d69a74]" name="testLogin" duration-ms="16086" started-at="2014-04-15T10:53:37Z" description="Test Login" data-provider="Data-Provider-Function" finished-at="2014-04-15T10:53:53Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[class java.lang.String]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[[Ljava.lang.String;@71c88986]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.fail(Assert.java:101)
	at hub.utilities.UserHubLoginUtil.testHubLoginSuccess(UserHubLoginUtil.java:81)
	at hub.test.LoginTest.testLogin(LoginTest.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:335)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:330)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogin -->
        <test-method status="PASS" signature="reinitializeBrowser()[pri:0, instance:hub.test.LoginTest@72d69a74]" name="reinitializeBrowser" is-config="true" duration-ms="10585" started-at="2014-04-15T10:53:53Z" finished-at="2014-04-15T10:54:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reinitializeBrowser -->
        <test-method status="PASS" signature="teardown()[pri:0, instance:hub.test.LoginTest@72d69a74]" name="teardown" is-config="true" duration-ms="82" started-at="2014-04-15T10:54:04Z" finished-at="2014-04-15T10:54:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- hub.test.LoginTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
